language: c
compiler:
  - clang
  - gcc
before_script:
  - sudo add-apt-repository ppa:dns/gnu -y
  - sudo apt-get update -q
  - sudo apt-get install --only-upgrade autoconf
  - sudo apt-get install --only-upgrade automake
script: ./configure && make && make check
